# Generated by Django 5.0.3 on 2024-03-27 11:54

import server.models
import server.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_category_icon_alter_server_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.channel_banner_upload_path, validators=[server.validators.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='channel',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.channel_icon_upload_path, validators=[server.validators.validate_icon_image_size, server.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=server.models.category_icon_upload_path, validators=[server.validators.validate_icon_image_size]),
        ),
    ]
